services:
  app:
    container_name: app
    depends_on:
      - db
    restart: on-failure
    build: backend
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      - POSTGRES_DB=person_db
      - POSTGRES_PASSWORD=$ENV_POSTGRES_PASSWORD
      - APP_PROFILE=dev-docker
    networks:
      - spring-postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "55432:80"
    networks:
      - spring-postgres
  db:
    image: postgres:15.2
    container_name: spring-postgres-db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=person_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  db-data:
secrets:
  db-password:
    file: db-pw/password.txt
networks:
  spring-postgres:
    name: spring-postgres